### ISSUE TITLE
Adding visual studio ignores

### ISSUE THREAD

**Issue by lyzerk** [HalitU/singularPoll#4]
We should ignore bin/obj folders and so on

Reference: [.gitignore](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore)

https://github.com/HalitU/singularPoll/blob/a821de5683ceeaf2baabf929d30c7f82ad8c2ae2/.gitignore#L27

**Comment by HalitU** [comment]
Fixed with updated .gitignore
